### ISSUE TITLE
responder

### ISSUE THREAD

**Issue by sec13b** [ShutdownRepo/ShadowCoerce#1]
can you write your responder command , and what version you use?

**Comment by fgeek** [comment]
@sec13b did you try
```
Responder.py -I interface -A
```
or
```
Responder.py -I interface
```
You can see interface name by running:
```
ip a
``` 
I believe version should not be relevant, but try also with latest in case of issues. You might need sudo to listen to network traffic in low ports.

**Comment by ShutdownRepo** [comment]
Yup, should be something like mentioned above

**Comment by sec13b** [comment]
I try .
thank you
